name: padelio-app
services:
  field-service:
    container_name: field-service
    platform: linux/amd64
    image: masadamsahid/padelio-field-service:2
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env