name: padel-booking-app
services:
  field-service:
    container_name: field-service
    platform: linux/amd64
    image: masadamsahid/padel-booking-app-field-service:1
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env